import "./globals.css";
import Link from 'next/link';
import Image from "next/image";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body>
        <header>
          <Image 
            src="wingLogo/wingLogo.svg"
            width={130}
            height={111}
          />
          <h1>Wing&apos;s HomePage</h1>
          <nav>
            <Link className='headerLinkTo' href='./'>Home</Link>
            <Link className='headerLinkTo' href='./about'>About Me</Link>
            <Link className='headerLinkTo' href='./contact'>Contacts</Link>
          </nav>
        </header>
        {children}
        <footer>
          <p>&copy; 2025 Wing. 無断転載・無断改変を禁じます．</p>
          <div className="footerContainer">
            <p>連絡先：</p>
            <a href="mailto:wing@me.wing.osaka">wing@me.wing.osaka</a>
          </div>
          <div className="footerContainer">
            <p>ブログ：</p>
            <a href="./SNS/Blog" target="_blank">https://blog.wing.osaka/posts</a>
          </div>
          <div className="footerContainer">
            <p>ダウンロード：</p>
            <Link href="/downloads">https://wing.osaka/downloads</Link>
          </div>
        </footer>
      </body>
    </html>
  );
}
